In [62]:
import pandas as pd
import numpy as np


In [3]:
pd.__version__

'2.3.1'

In [54]:
github_url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv'
df= pd.read_csv(github_url)


In [55]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [15]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [27]:
df.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [ ]:
cars=df[df['origin']=='Asia']
cars['fuel_efficiency_mpg'].max

np.float64(23.759122836520497)

In [56]:
df['horsepower'].median()


np.float64(149.0)

In [57]:
df['horsepower'].mode()
df['horsepower'].fillna(df['horsepower'].mode()[0], inplace=True)
df['horsepower'].median()


/tmp/ipykernel_7284/1067347948.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(df['horsepower'].mode()[0], inplace=True)


np.float64(152.0)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [94]:
X = cars[['vehicle_weight','model_year']].head(7)
X
X.shape

(7, 2)

In [108]:

XT = X.T
XT.shape
XT

8            12           14           20  \
vehicle_weight  2714.21931  2783.868974  3582.687368  2231.808142   
model_year      2016.00000  2010.000000  2007.000000  2011.000000   

                         21           34           38  
vehicle_weight  2659.431451  2844.227534  3761.994038  
model_year      2016.000000  2014.000000  2019.000000

In [110]:
XTX = XT.dot(X)
XTX
XTX.shape
XTX

vehicle_weight    model_year
vehicle_weight    6.224833e+07  4.143122e+07
model_year        4.143122e+07  2.837334e+07

In [ ]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv
XTX_inv.shape

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [113]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y.shape
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [118]:
V=XTX_inv.dot(X.T)
V.shape
V

array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
        -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
         4.65094049e-04],
       [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
         6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
        -6.07979633e-04]])

In [120]:
W=V.dot(y)
w.shape
w

array([0.01386421, 0.5049067 ])